# Generated by Django 5.1.1 on 2025-01-04 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('initiator_id', models.CharField(max_length=255)),
                ('receiver_id', models.CharField(max_length=255)),
                ('shop_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['room_id'], name='videocall_v_room_id_69df05_idx'), models.Index(fields=['initiator_id', 'receiver_id'], name='videocall_v_initiat_cca538_idx'), models.Index(fields=['shop_id', 'status'], name='videocall_v_shop_id_e9efc6_idx')],
            },
        ),
    ]
