# Generated by Django 5.1.1 on 2025-01-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('shop_id', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('connection_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['shop_id', 'is_online'], name='videocall_u_shop_id_f457b7_idx'), models.Index(fields=['user_id', 'last_seen'], name='videocall_u_user_id_a92578_idx')],
            },
        ),
    ]
