# Generated by Django 5.1.1 on 2025-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0002_useronlinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronlinestatus',
            name='sub_admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
