# Generated by Django 5.1.1 on 2024-11-18 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ration_shops_app', '0004_remove_subadminauth_auth_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(choices=[('YELLOW', 'AAY Card - Yellow'), ('PINK', 'Priority Card - Pink'), ('BLUE', 'Non-Priority Subsidy Card - Blue'), ('WHITE', 'Non-Priority Card - White')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('relation', models.CharField(choices=[('SELF', 'Self'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=10)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('household_address', models.TextField()),
                ('head_name', models.CharField(max_length=255)),
                ('head_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(150)])),
                ('head_monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('head_aadhaar', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending for Shop Verification'), ('SHOP_VERIFIED', 'Verified by Shop'), ('SHOP_REJECTED', 'Rejected by Shop'), ('ADMIN_APPROVED', 'Approved by Admin'), ('ADMIN_REJECTED', 'Rejected by Admin'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=15)),
                ('shop_verified_at', models.DateTimeField(blank=True, null=True)),
                ('shop_verification_notes', models.TextField(blank=True, null=True)),
                ('admin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_verification_notes', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(help_text='Upload supporting documents (PDF/Images)', upload_to='ration_card_documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_verified_cards', to='ration_shops_app.subadminauth')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ration_cards_app.cardtype')),
                ('family_members', models.ManyToManyField(related_name='ration_cards', to='ration_cards_app.familymember')),
                ('registered_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_cards', to='ration_shops_app.rationshop')),
                ('shop_verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_verified_cards', to='ration_shops_app.subadminauth')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card_number'], name='ration_card_card_nu_a870c8_idx'), models.Index(fields=['head_aadhaar'], name='ration_card_head_aa_e3c976_idx'), models.Index(fields=['status'], name='ration_card_status_df90fb_idx')],
            },
        ),
    ]
