# Generated by Django 5.1.1 on 2024-11-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='aadhaar_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
