# Generated by Django 5.1.1 on 2024-11-19 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0002_alter_familymember_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ration_cards_app.cardtype'),
        ),
    ]
