# Generated by Django 5.1.1 on 2024-11-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0003_alter_rationcard_card_type'),
        ('ration_shops_app', '0004_remove_subadminauth_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcard',
            name='requester_email',
            field=models.EmailField(default='xyz@gmail.com', help_text='User email from JWT token', max_length=254),
        ),
        migrations.AddField(
            model_name='rationcard',
            name='requester_id',
            field=models.CharField(default=12, help_text='User ID from JWT token', max_length=100),
        ),
        migrations.AddIndex(
            model_name='rationcard',
            index=models.Index(fields=['requester_id'], name='ration_card_request_6e5cba_idx'),
        ),
    ]
