# Generated by Django 5.1.1 on 2024-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0004_rationcard_requester_email_rationcard_requester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='requester_email',
            field=models.EmailField(help_text='User email from JWT token', max_length=254),
        ),
        migrations.AlterField(
            model_name='rationcard',
            name='requester_id',
            field=models.CharField(help_text='User ID from JWT token', max_length=100),
        ),
    ]
