# Generated by Django 5.1.1 on 2024-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0005_alter_rationcard_requester_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='name',
            field=models.CharField(choices=[('antyodaya', 'Antyodaya Anna Yojana (AAY)'), ('priority_household', 'Priority Household (PHH)'), ('non_priority_household', 'Non-Priority Household (NPHH)'), ('antodaya_anna_scheme', 'Antodaya Anna Scheme'), ('anna_poorana_scheme', 'Anna Poorana Scheme')], help_text="Select the type of ration card from Kerala's official categories", max_length=50, unique=True),
        ),
    ]
