# Generated by Django 5.1.1 on 2024-12-06 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0006_alter_cardtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFromSrockService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_category', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('max_quantity_per_person', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per kg/litre/gram.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
