# Generated by Django 5.1.1 on 2024-12-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0007_datafromsrockservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcard',
            name='max_quantities',
            field=models.JSONField(blank=True, help_text='JSON field to store maximum quantities for different items', null=True),
        ),
    ]
