# Generated by Django 5.1.1 on 2024-12-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0008_rationcard_max_quantities'),
        ('ration_shops_app', '0006_subadminauth_is_subadmin_subadminauth_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='shop_verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_verified_cards', to='ration_shops_app.rationshop'),
        ),
    ]
