# Generated by Django 5.1.1 on 2024-12-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0010_alter_rationcard_admin_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='status',
            field=models.CharField(default='PENDING', max_length=15),
        ),
    ]
