# Generated by Django 5.1.1 on 2024-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0011_alter_rationcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='max_quantities',
            field=models.IntegerField(blank=True, help_text='JSON field to store maximum quantities for different items', null=True),
        ),
    ]
