# Generated by Django 5.1.1 on 2024-12-12 03:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0012_alter_rationcard_max_quantities'),
        ('stocks_app', '0003_alter_quota_unique_together_quota_month_quota_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.item')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.quota')),
                ('ration_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration_cards_app.rationcard')),
            ],
            options={
                'unique_together': {('ration_card', 'item', 'quota')},
            },
        ),
    ]
