# Generated by Django 5.1.1 on 2024-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0014_quotaallocation_remaining_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
