# Generated by Django 5.1.1 on 2024-12-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0016_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcard',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
