# Generated by Django 5.1.1 on 2025-01-24 14:10

import ration_cards_app.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0017_rationcard_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='face_image_media',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
        migrations.AddField(
            model_name='rationcard',
            name='supporting_document_media',
            field=models.FileField(blank=True, help_text='Upload supporting documents (PDF/Images)', null=True, upload_to='ration_card_documents/'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='face_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=ration_cards_app.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='rationcard',
            name='supporting_document',
            field=models.FileField(help_text='Upload supporting documents', storage=storages.backends.s3.S3Storage(), upload_to=ration_cards_app.models.custom_upload_to),
        ),
    ]
