apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ronygeorgen/api-gateway:latest
        ports:
        - containerPort: 8005
        envFrom:
        - configMapRef:
            name: common-configmap
        - secretRef:
            name: common-secret
        env:
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: common-configmap
              key: API_GATEWAY_DB
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8005
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8005
        #   initialDelaySeconds: 30
        #   periodSeconds: 20