# Generated by Django 5.1.1 on 2024-12-08 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ration_cards_app', '0011_alter_rationcard_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regular', 'Regular Quota'), ('additional', 'Additional Quota')], help_text='Select either Regular Quota or Additional Quota.', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('litre', 'Litre'), ('gm', 'Gram')], default='kg', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quantity', models.FloatField(help_text='Maximum quantity allowed for this item.', validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per kg/litre/gram.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='ration_cards_app.cardtype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='stocks_app.item')),
            ],
            options={
                'verbose_name_plural': 'Quotas',
                'unique_together': {('card_type', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(help_text='Unique identifier of the ration shop.', max_length=100)),
                ('total_quantity', models.FloatField(help_text='Total stock assigned to the ration shop.', validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_quantity', models.FloatField(help_text='Remaining stock after distribution.', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_stocks', to='stocks_app.item')),
            ],
            options={
                'unique_together': {('shop_id', 'item')},
            },
        ),
    ]
