# Generated by Django 5.1.1 on 2024-12-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0006_subadminauth_is_subadmin_subadminauth_is_superadmin'),
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstock',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='ration_shops_app.rationshop'),
        ),
    ]
