# Generated by Django 5.1.1 on 2024-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_cards_app', '0012_alter_rationcard_max_quantities'),
        ('stocks_app', '0002_alter_shopstock_shop_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quota',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quota',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together={('card_type', 'item', 'month', 'year')},
        ),
    ]
