"""
Django settings for ration_shop_service project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import environ
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DEBUG=(bool,False)
)
environ.Env.read_env(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'ration_shops_app',
    'ration_cards_app',
    'stocks_app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ration_shop_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ration_shop_service.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'PATCH','PUT', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = ['Authorization', 'Content-Type'] 

# ration-cards-app
RATION_CARDS_APP_REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': [
'ration_cards_app.authentication.SubAdminJWTAuthentication',
'ration_cards_app.authentication.UserJWTAuthenticationCards',
]
}
# ration-shops-app 
RATION_SHOPS_APP_REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': [
'ration_shops_app.authentication.CookieJWTAuthentication',
'ration_shops_app.authentication.UserJWTAuthentication',
]
}
# stocks-app 
STOCKS_APP_REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': [
'stocks_app.authentication.CookieJWTAuthenticationStock',
'stocks_app.authentication.UserJWTAuthenticationStock',
]
}

# Redis Configuration
REDIS_URL = env('REDIS_URL')  # Adjust as per your Redis setup

# Twilio Configuration
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER')

# OTP Configuration
OTP_EXPIRATION_TIME = 300  
OTP_RESEND_COOLDOWN = 30   
MAX_OTP_ATTEMPTS = 3


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': os.environ.get('SECRET_KEY'),
    'VERIFYING_KEY': None,
    'ALGORITHM': 'HS256',
}

# Kafka Settings
KAFKA_BOOTSTRAP_SERVERS = 'kafka.default.svc.cluster.local:9092'

KAFKA_TOPIC_USER_EVENTS = 'user_events'
KAFKA_TOPIC_RATION_SHOP_CREATION_EVENTS = 'ration_shop_events'

KAFKA_CONSUMER_GROUP = 'ration_shop_service_user_consumer'
KAFKA_CLIENT_ID = 'ration_shop_service_provider'

# below kafka for ration card
KAFKA_TOPIC_ORDER_EVENTS = 'order_events_topic'
KAFKA_CONSUMER_GROUP_ORDERS = 'ration_shop_order_consumer'



# Model file paths
SHAPE_PREDICTOR_PATH = os.path.join(BASE_DIR, 'ml_models', 'shape_predictor_68_face_landmarks.dat')
LIVENESS_MODEL_PATH = os.path.join(BASE_DIR, 'ml_models', 'model.h5')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Subdirectories for specific file types
VIDEO_DIR = os.path.join(MEDIA_ROOT, 'liveness_videos')  # Video storage
IMAGE_DIR = os.path.join(MEDIA_ROOT, 'liveness_images')  # Image storage
TEMP_FRAME_DIR = os.path.join(MEDIA_ROOT, 'temp_frames')  # Temporary frame storage

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
