# Generated by Django 5.1.1 on 2024-11-20 16:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('antyodaya', 'Antyodaya Anna Yojana (AAY)'), ('priority_household', 'Priority Household (PHH)'), ('non_priority_household', 'Non-Priority Household (NPHH)'), ('antodaya_anna_scheme', 'Antodaya Anna Scheme'), ('anna_poorana_scheme', 'Anna Poorana Scheme')], help_text="Select the type of ration card from Kerala's official categories", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regular', 'Regular Quota'), ('additional', 'Additional Quota')], help_text='Select either Regular Quota or Additional Quota.', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('litre', 'Litre'), ('piece', 'Piece')], default='kg', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quantity', models.FloatField(help_text='Maximum quantity allowed for this item.', validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per kg/litre/piece.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='product_management.cardtype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='product_management.item')),
            ],
            options={
                'verbose_name_plural': 'Quotas',
                'unique_together': {('card_type', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(help_text='Unique identifier of the ration shop.', max_length=100)),
                ('total_quantity', models.FloatField(help_text='Total stock assigned to the ration shop.', validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_quantity', models.FloatField(help_text='Remaining stock after distribution.', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_stocks', to='product_management.item')),
            ],
            options={
                'unique_together': {('shop_id', 'item')},
            },
        ),
    ]
