# Generated by Django 5.1.1 on 2024-12-06 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('litre', 'Litre'), ('gm', 'Gram')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='quota',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Price per kg/litre/gram.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
