# Generated by Django 5.1.1 on 2024-11-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_order_status_alter_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
    ]
