# Generated by Django 5.1.1 on 2024-12-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
