# Generated by Django 5.1.1 on 2025-01-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_order_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('session_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['idempotency_key'], name='order_manag_idempot_552790_idx')],
            },
        ),
    ]
