# Generated by Django 5.1.1 on 2025-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_stripepaymentintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepaymentintent',
            name='idempotency_key',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='stripepaymentintent',
            name='session_id',
            field=models.TextField(),
        ),
    ]
