apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
data:
  API_GATEWAY_DB: "an_api_gateway"
  # User Service DB
  USER_SERVICE_DB: "an_user_service"
  # Order Service DB
  ORDER_SERVICE_DB: "an_order_service"
  # Ration Shop Service DB
  RATION_SHOP_DB: "an_ration_shop_service"
  # Notification Service DB
  NOTIFICATION_DB: "an_notification_service"

  DEBUG: "True"
  ALLOWED_HOSTS: "*"

  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"

  REDIS_HOST: "redis"
  REDIS_URL: "redis://redis:6379/0"
  REDIS_PORT: "6379"

  KAFKA_HOST: "kafka:9092"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"


  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"

  USER_SERVICE_URL: "user-service:8000"
  ORDER_SERVICE_URL: "order-service:8003"
  RATION_SHOP_SERVICE_URL: "ration-shop-service:8002"
  NOTIFICATION_SERVICE_URL: "notification-service:8004"