# Generated by Django 5.1.1 on 2024-11-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationshop',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ration_shops_app.subadminauth'),
        ),
    ]
