# Generated by Django 5.1.1 on 2024-11-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0002_alter_rationshop_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
