# Generated by Django 5.1.1 on 2024-11-15 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0003_rationshop_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadminauth',
            name='auth_token',
        ),
        migrations.AddField(
            model_name='rationshop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rationshop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subadminauth',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('image_type', models.CharField(choices=[('PROFILE', 'Profile Picture'), ('SHOP', 'Shop Image')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ration_shops_app.rationshop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('image_type', 'PROFILE'), ('is_active', True)), fields=('shop',), name='unique_active_profile_picture')],
            },
        ),
    ]
