# Generated by Django 5.1.1 on 2024-11-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0004_remove_subadminauth_auth_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminauth',
            name='auth_token',
        ),
    ]
