# Generated by Django 5.1.1 on 2024-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0005_remove_adminauth_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminauth',
            name='is_subadmin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subadminauth',
            name='is_superadmin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
