# Generated by Django 5.1.1 on 2025-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0006_subadminauth_is_subadmin_subadminauth_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopimage',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='image_media',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
