# Generated by Django 5.1.1 on 2025-01-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shops_app', '0007_shopimage_cloudinary_public_id_shopimage_image_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rationshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
