apiVersion: apps/v1
kind: Deployment
metadata:
  name: ration-shop-service
  labels:
    app: ration-shop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ration-shop-service
  template:
    metadata:
      labels:
        app: ration-shop-service
    spec:
      containers:
      - name: ration-shop-service
        image: ronygeorgen/ration-shop-service:latest
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: common-configmap
        - secretRef:
            name: common-secret
        env:
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: common-configmap
              key: RATION_SHOP_DB
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8002
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8002
        #   initialDelaySeconds: 30
        #   periodSeconds: 20