# Generated by Django 5.1.1 on 2025-01-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user_id', 'order_id', 'message')},
        ),
    ]
