# Generated by Django 5.1.1 on 2024-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admins_app', '0003_rationshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationshop',
            name='shop_id',
            field=models.IntegerField(unique=True),
        ),
    ]
