# Generated by Django 5.1.1 on 2025-01-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admins_app', '0004_alter_rationshop_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
