# Generated by Django 5.1.1 on 2025-01-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admins_app', '0005_account_latitude_account_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='google_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
