# Generated by Django 5.1.1 on 2025-01-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_admins_app', '0007_account_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email_verification_token_created',
        ),
    ]
