# Generated by Django 5.1.1 on 2025-01-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_admins_app', '0009_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
